### ISSUE TITLE
Custom whiteboard application!

### ISSUE THREAD

**Issue by RamanHacks** [netless-io/flat#1]
How to enable only RTC Audio feature (and not video feature) when building a custom whiteboard application?

**Comment by leavesster** [comment]
Sorry for late reply. We have only recently started building this project.

As RTC is not a basic service we provide, we have only wrapped it up as a third party and cannot provide a more specific response at this time. However, the requirement will be met later.


You can also wait for a response to the issue AgoraIO-Usecase/eEducation#5 you raised with the corresponding rtc vendor.

**Comment by RamanHacks** [comment]
Thanks for the response. I had been looking to integrate the whiteboard api with my application. It would have been cherry on the top had the audio only feature was provided. Nonetheless, the API is **awesome**. Looking forward for more features added to it.
