### ISSUE TITLE
[bug]: flat-web failed to startup

### ISSUE THREAD

**Issue by meimosor** [netless-io/flat#1006]
The web terminal failed to start, any good suggestions?
![image](https://user-images.githubusercontent.com/31975932/137429008-9a978421-90c0-4869-aba8-0960ed88ad95.png)

**Comment by BlackHole1** [comment]
@hyrious

**Comment by hyrious** [comment]
It seems <ins>node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js</ins> is found correctly, but edited wrong. Can you manually find this file and see if it includes such line?
```js
import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
```

**Comment by BlackHole1** [comment]
It's strange, it's fine under macos, but under windows it reports an error

<img width="1497" alt="图片" src="https://user-images.githubusercontent.com/8198408/137430001-fd960e26-5095-4c8e-8bec-5754dcf88cba.png">

Is it caused by the system path separator? @hyrious can you help with this problem?

**Comment by meimosor** [comment]
> It seems node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js is found correctly, but edited wrong. Can you manually find this file and see if it includes such line?
> 
> ```js
> import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
> ```

![image](https://user-images.githubusercontent.com/31975932/137430892-b34789a8-d756-4504-9ad5-38ea446aaa1d.png)
![image](https://user-images.githubusercontent.com/31975932/137430942-9b72b779-8d93-4249-b5cc-568b206e2387.png)
