### ISSUE TITLE
Remove component code from store

### ISSUE THREAD

**Issue by crimx** [netless-io/flat#1019]
Use a property to switch Preview Modal:

https://github.com/netless-io/flat/blob/f9f9932997b7cb3923bc990bddc72812f6e8f7ba/desktop/renderer-app/src/pages/CloudStoragePage/store.tsx#L382-L390

Style files should be alongside with the component:

https://github.com/netless-io/flat/blob/f9f9932997b7cb3923bc990bddc72812f6e8f7ba/desktop/renderer-app/src/pages/CloudStoragePage/store.less#L1

**Comment by BlackHole1** [comment]
@crimx
