### ISSUE TITLE
Where to find the development documentation？

### ISSUE THREAD

**Issue by meimosor** [netless-io/flat#1096]
Where to find the development documentation？

**Comment by hyrious** [comment]
There is [Development Mode](https://github.com/netless-io/flat#development-mode) in the readme.

**Comment by BlackHole1** [comment]
We are sorry that we do not have particularly much time to improve the documentation at the moment.
You can start the program by using the brief in the README([Development Mode](https://github.com/netless-io/flat#development-mode))

**Comment by meimosor** [comment]
How to integrate it in vue3.0?

**Comment by BlackHole1** [comment]
currently we have no plans to support vue
