### ISSUE TITLE
[chore]: replace react router custom loop by offical api 

### ISSUE THREAD

**Issue by Cyberhan123** [netless-io/flat#1100]
Implementation of using [useroutes](https://reactrouter.com/docs/en/v6/api#useroutes) instead of https://github.com/netless-io/flat/blob/main/web/flat-web/src/AppRoutes/index.tsx#L15

cc  @BlackHole1 @hyrious @LitoMore

**Comment by BlackHole1** [comment]
LGTM
cc @crimx @Cheerego7

**Comment by hyrious** [comment]
What about other libraries that depend on old react-router-dom?
For example `react-router-last-location` has:
```json
  "peerDependencies": {
    "prop-types": "^15.6.0",
    "react": "^15.5.4 || ^16.0.0",
    "react-dom": "^15.5.4 || ^16.0.0",
    "react-router-dom": "^4.1.1 || ^5.0.1"
  },
```
We'd better avoid two different versions of same library in one project.

**Comment by crimx** [comment]
This is a v6 feature which requires a migration from our v5 `react-router` dependency.

> The `useRoutes` hook is the functional equivalent of `<Routes>`

AFAICT the only benefit of using `useRoutes` over `<Routes>` is optional JSX. But the code example uses JSX for `element` anyway, so I think the benefit is negligible.

Thank you for bringing this to our attention.

**Comment by Cyberhan123** [comment]
> What about other libraries that depend on old react-router-dom? For example `react-router-last-location` has:
> 
> ```json
>   "peerDependencies": {
>     "prop-types": "^15.6.0",
>     "react": "^15.5.4 || ^16.0.0",
>     "react-dom": "^15.5.4 || ^16.0.0",
>     "react-router-dom": "^4.1.1 || ^5.0.1"
>   },
> ```
> 
> We'd better avoid two different versions of same library in one project.

That my issues in https://github.com/hinok/react-router-last-location/issues/67

**Comment by Cyberhan123** [comment]
> This is a v6 feature which requires a migration from our v5 `react-router` dependency.
> 
> > The `useRoutes` hook is the functional equivalent of `<Routes>`
> 
> AFAICT the only benefit of using `useRoutes` over `<Routes>` is optional JSX. But the code example uses JSX for `element` anyway, so I think the benefit is negligible.
> 
> Thank you for bringing this to our attention.

You‘r right ,Let's wait the bullet fly for a while
