### ISSUE TITLE
keep packages/flat-types build with tsc

### ISSUE THREAD

**Issue by Cyberhan123** [netless-io/flat#1131]
Using vite to build ts is not a good idea，detail see https://vitejs.dev/guide/features.html#typescript

**Comment by BlackHole1** [comment]
@crimx @hyrious

**Comment by hyrious** [comment]
It is **ok**, but we'd better make sure not ~~using~~ exporting ts features that are not supported in vite environment, which need type systems, like decorators and `const enum`, see https://esbuild.github.io/content-types/#typescript-caveats.

BTW, esbuild _just_ partially supported sibling namespaces (with no support for namespace across files) in the next breaking verion (0.14.x). There are some other features banned too.

**Comment by BlackHole1** [comment]
That is, we have to choose between better typing and compilation speed, right? @hyrious

**Comment by hyrious** [comment]
I'm not sure whether decorators and namespaces are <q>better typing</q>.

In fact, we have chosen once when we decided to use tsconfig `"paths"` to redirect import path to flat-types and flat-components folders. This way, all types in those folders can not use banned features otherwise the vite in flat-web won't work properly.

**Comment by BlackHole1** [comment]
how about `swc`?

**Comment by crimx** [comment]
The [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules) option basically means you should write ts code in a certain manner. Strong typing won't be affected by following the isolatedModules pattern. Missing features like `const enum` are fine as we don't use them in Flat (There are better alternatives even if we want to).

The problem of tsc is that it's considerably slow comparing to transpilers like babel and esbuild. For better DX we may keep the vite for bundling and let CI perform the `tsc --noEmit` check.

**Comment by crimx** [comment]
> how about `swc`?

@BlackHole1  Unlike babel and esbuild which are transpilers, swc is a rewrite of tsc which requires greater amount of works. It is still at a very early stage with tons of bugs. I think we should wait and see how the swc project goes.

**Comment by BlackHole1** [comment]
> There are better alternatives even if we want to

Can you give me an example?

cc: @crimx

**Comment by Cyberhan123** [comment]
Can we use vite to build ts type yet？

**Comment by crimx** [comment]
@BlackHole1 https://stackoverflow.com/a/60041791

Also the issue of `enum` is that it enforce downstream users to obtain the `enum` object for usage. This is a PITA in practice.

In the telebox project we use the combination of `enum` and `union` which exposes APIs that allow downstream users to pass in `enum` or `string`(both are strongly typed).

https://github.com/netless-io/telebox-insider/blob/48ea536aa6c6c21f2d77b50a75da4c59b67d8ee2/src/TeleBox/constants.ts#L1-L5

https://github.com/netless-io/telebox-insider/blob/48ea536aa6c6c21f2d77b50a75da4c59b67d8ee2/src/TeleBox/typings.ts#L15

**Comment by hyrious** [comment]
> Can we use vite to build ts type yet？

No, it can't. Only `tsc` itself could build d.ts files.

But we don't need d.ts files, just use the source file is enough.

**Comment by Cyberhan123** [comment]
> > Can we use vite to build ts type yet？
> 
> No, it can't. Only `tsc` itself could build d.ts files.
> 
> But we don't need d.ts files, just use the source file is enough.

we use vite in dev mode can remove tsc build,and just keep it in build mode,right?

**Comment by hyrious** [comment]
In build mode, we don't need it too now:
- In flat-web and renderer-app, we are using `paths` in tsconfig to read the real source file.
- In flat-types, this package is never published (and eventually we will not treat it as package any more), so building it does not mean anything.
