### ISSUE TITLE
[discussion]: vite is ready for storybook?

### ISSUE THREAD

**Issue by Cyberhan123** [netless-io/flat#1143]
In https://github.com/netless-io/telebox-insider vite is ready for storybook

**Comment by Cyberhan123** [comment]
Is flat component need public storybook to somewhere? 

@hyrious @BlackHole1

**Comment by hyrious** [comment]
> Is flat component need public storybook to somewhere?

Yes, at https://netless-io.github.io/flat.

@crimx May you have a look at storybook on vite?

**Comment by Cyberhan123** [comment]
After my investigation last week, I found that the coexistence of vite and webpack is not a bad idea so far.

**Comment by crimx** [comment]
> In https://github.com/netless-io/telebox-insider vite is ready for storybook

@Cyberhan123  Nice observation! Flat requires more features from storybook than telebox-insider which is still in development. We will migrate to storybook-builder-vite once https://github.com/eirslett/storybook-builder-vite/issues/2#issuecomment-823064989 is resolved.

**Comment by Cyberhan123** [comment]
Let the bullet fly for a while，I will keep this issue，and provide a PR with [WIP] label

**Comment by hyrious** [comment]
We also want to move to pnpm once storybookjs/storybook#13428 get resolved.

**Comment by Cyberhan123** [comment]
> We also want to move to pnpm once [storybookjs/storybook#13428](https://github.com/storybookjs/storybook/issues/13428) get resolved.

The storybook plugin have an new version for suport react typescript, I'll try it soon.

**Comment by Cyberhan123** [comment]
Synchronize the progress, I may need to fix this first

 https://github.com/eirslett/storybook-builder-vite/issues/233#issuecomment-1035720208

**Comment by crimx** [comment]
Storybook 6.5 has brought vite builder into the official core.
 https://storybook.js.org/blog/storybook-6-5/#vite-builder-for-instant-rebuilds

**Comment by Cyberhan123** [comment]
> Storybook 6.5 has brought vite builder into the official core. https://storybook.js.org/blog/storybook-6-5/#vite-builder-for-instant-rebuilds

I'll start investigating this migration
