### ISSUE TITLE
[discussion]: Questions about the open-source of this project

### ISSUE THREAD

**Issue by shunFSKi** [netless-io/flat#1158]
感谢你们的开源，想咨询一下这是基于声网传输服务的收费开源项目吗？

## Update (i18n)
Thank you for the open source, I would like to inquire about this is based on the sound network transmission service fee open source project?

**Comment by BlackHole1** [comment]
This project is based on the Agora sdk for development. Although the Agora sdk is charged, this project is free to use without any restrictions.

**Comment by shunFSKi** [comment]
所以rtc和rtm相关的授权并不会涉及到收费？

## Update(i18n)
So rtc and rtm related licensing doesn't involve fees?

**Comment by BlackHole1** [comment]
This is an open source project for the world, so for the convenience of others, please use English.

**Comment by BlackHole1** [comment]
There will be a fee, but that's for us, not the user. So you can use it for free, don't worry.
