### ISSUE TITLE
[feat]: permission request requires i18n support in macOS

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#1172]
see: https://github.com/netless-io/flat/blob/2b89c56b378e457e359c7732e13248560847db94/desktop/main-app/electron-builder.yml#L21-L22

we need support Chinese desc

**Comment by BlackHole1** [comment]
@Leooeloel Please provide a description in Chinese

**Comment by Leooeloel** [comment]
Please follow the following prompts in English and Chinese.

In order to work properly, Flat needs  permission to access microphone

In order to work properly, Flat needs permission to access camera

为了能够正常使用，Flat 需要访问麦克风的权限

为了能够正常使用，Flat 需要访问摄像头的权限

**Comment by LitoMore** [comment]
The sentence below makes me feel that the user must provide permissions, otherwise the software will not be usable at all. And I don't know what it needs permissions for, and when it will be used.

```
In order to work properly, Flat needs permission to access...
```

FYI: https://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/

**Comment by Leooeloel** [comment]
Yes, I do confuse users with this approach, and I will reorganize the requirements to ensure a classroom experience without violating user privacy.

Thanks for the reminder, I'll ask you to review it when it's ready.

**Comment by Matrixbirds** [comment]
Any work in progress needs to update? 
cc: @Leooeloel

**Comment by Leooeloel** [comment]
We don't ask users for permissions when they first open flat.

Currently flat does not actively ask for permissions from users, the prompt to ask for permissions in flat is triggered by the user. For example, when a user clicks to open the camera, but does not give flat permission to use the camera, this prompt will appear. This way the user doesn't feel too confused.

Here we need your help to update the authorization prompt.


> Please follow the following prompts in English and Chinese.
> 
> In order to work properly, Flat needs permission to access microphone
> 
> In order to work properly, Flat needs permission to access camera
> 
> 为了能够正常使用，Flat 需要访问麦克风的权限
> 
> 为了能够正常使用，Flat 需要访问摄像头的权限

**Comment by Leooeloel** [comment]
cc: @Matrixbirds @LitoMore @BlackHole1

**Comment by BlackHole1** [comment]
Okey
