### ISSUE TITLE
[bug]: Nav does not need to re-render, when switching tab

### ISSUE THREAD

**Issue by syt-honey** [netless-io/flat#1180]
**End**
[flat-web](https://flat-web.whiteboard.agora.io/)

**What steps will reproduce the problem?**
1. open [flat-web](https://flat-web.whiteboard.agora.io/) link, and login
2. switch tab
3. nav will be re-rendered

**What is the expected result?**
When switching tab, nav does not need to re-render

**Comment by syt-honey** [comment]
Addition: Is there a template to give others feedback Issue or submit PR? @BlackHole1

**Comment by BlackHole1** [comment]
Sorry, I don't quite understand, can you record a video to help us understand your question?

**Comment by BlackHole1** [comment]
> Addition: Is there a template to give others feedback Issue or submit PR? @BlackHole1

Good idea! I will create template later

**Comment by hyrious** [comment]
It used to work (#728), but was blinking again (#1038). We have to investigate it.
