### ISSUE TITLE
[bug]: mouse cannot be displayed during screen sharing on desktop

### ISSUE THREAD

**Issue by Autumn-one** [netless-io/flat#1198]

**Comment by BlackHole1** [comment]
Please wait, I'll look at it now

**Comment by BlackHole1** [comment]
The problem has been reproduce and we will be fixing this in the near future.
Thank you for your feedback

<details>
    <summary>中文</summary>
    这个问题已经复现，我们将在近期修复这个问题。
    <br />
    感谢你的反馈
</details>

**Comment by BlackHole1** [comment]
This issue has been fixed and will be carried in the next release.

<details>
    <summary>中文</summary>
    此问题已经修复，将会在下个版本发布中携带上。
</details>
