### ISSUE TITLE
Dart is more suitable alternative

### ISSUE THREAD

**Issue by findthewaytoios** [netless-io/flat#1201]
Dart is an object-oriented C language，Dart is a statically typed language that eliminates common sources of errors in JavaScript code. Dart supports type inference, so there is no need to include type boilerplate every time a variable or function is declared.Perhaps the most exciting feature of Dart is its availability outside the network.Perhaps the most exciting feature of Dart is its availability outside the network. Google's Flutter UI toolkit is a portable front-end framework that can be used on desktops, mobile devices and the Web to build native applications.     @bestony

**Comment by hyrious** [comment]
We have considered Flutter before, but there's no silver bullet. Our apps have to call the api of agora-rtc-sdk and white-web-sdk in the correct way, which have many differences in many platforms. Besides, we believe native clients will have better performance (although the desktop app is built on top of electron, not very native).

On top of that, many of us team members are front-end developers, using the react and similar tech is more acceptable and maintainable.

> Dart is an object-oriented C language

JS is an object-oriented C-lile language too.

> Dart is a statically typed language

Typings are good, but you take the consequences: Is it compiling slow? How to use it properly (i.e. needs some time to learn)? Do IDEs support it?

I believe there always exists some js code that can not be written in dart, where you have to pay for that.

> Dart supports type inference

TypeScript supports it too, in fact these `: typing` code are the code style enforced by eslint. Sometimes the IDE/editor can help us auto-complete them. They make codes more readable, but is not always needed.

> Perhaps the most exciting feature of Dart is its availability outside the network.

What's that mean? In fact to develop a _local-first_ app requires many additional thoughts and designs. I don't think a language can contribute any advances of it. Sorry if I think it wrong.
