### ISSUE TITLE
[bug]: Teacher side end hand up, student side microphone is not turned off

### ISSUE THREAD

**Issue by shunyue1320** [netless-io/flat#1202]
Overview of the problem:
1. start class
2. students raised their hands and then spoke
3. the teacher clicked to end but the students’ microphones were still ringing

Expected behavior:
Teacher clicks to end, student's microphone is turned off

Actual behavior:
Teacher clicks to end, student's microphone is not turned off

@bestony

**Comment by BlackHole1** [comment]
> the teacher clicked to end

clicked stop classroom button or else?

**Comment by shunyue1320** [comment]
> > the teacher clicked to end
> 
> clicked stop classroom button or else?

点击结束举手

**Comment by shunyue1320** [comment]
![image](https://user-images.githubusercontent.com/47295879/145744091-2803a5ce-ae72-4684-b308-c9817e83a96d.png)

**Comment by BlackHole1** [comment]
@hyrious

**Comment by bestony** [comment]
hi, @shunyue1320, please send your address, phone number, and name to my email address (bestony@linux.com), i will send you DAO.FM gift.
