### ISSUE TITLE
[discussion]: desktop/main-app

### ISSUE THREAD

**Issue by Cyberhan123** [netless-io/flat#1300]
We can use esbuild to accomplish this, the specific tasks still need to be investigated

- [x] Need support preload script
- [x] Need support hot-reload
- [x] Need support DotenvFlow
- [ ] Need support ESLintPlugin
- [x] Need support Electron logger

**Comment by Cyberhan123** [comment]
@BlackHole1 
Did I miss anything？And I don't have a good idea to make `eslint` and `dot env flow` support esbuild.Do you have any suggestions？

**Comment by BlackHole1** [comment]
@hyrious

**Comment by hyrious** [comment]
There's nothing difficult to support them in esbuild, you can have a look at the plugin api: https://esbuild.github.io/plugins/#using-plugins

For example, the eslint plugin have to gather input files through `onLoad` or `metafile`, then invoke eslint; the dot env plugin have to modify `initialOptions.define` before everything goes.

**Comment by Cyberhan123** [comment]
> There's nothing difficult to support them in esbuild, you can have a look at the plugin api: https://esbuild.github.io/plugins/#using-plugins
> 
> For example, the eslint plugin have to gather input files through `onLoad` or `metafile`, then invoke eslint; the dot env plugin have to modify `initialOptions.define` before everything goes.

Thanks

**Comment by BlackHole1** [comment]
we don't need `Electron logger`

**Comment by BlackHole1** [comment]
@Cyberhan123

**Comment by Cyberhan123** [comment]
@BlackHole1  I will finish this feature irecently, I have been busy with other things

**Comment by Cyberhan123** [comment]
So far there is no good solution for esbuild eslint plugin, The eslint will case performance issues. So I suggest not to integrate it for now.
@hyrious @BlackHole1
