### ISSUE TITLE
yarn run ship:mac 点击快速开始-任意选择-点击开始/系统检测-摄像头检测，出现白屏

### ISSUE THREAD

**Issue by way-jm** [netless-io/flat#1319]
![image](https://user-images.githubusercontent.com/18083432/150300497-67f99e32-b1cf-4a8b-8a3f-f9e320f61c2e.png)

**Comment by way-jm** [comment]
开发模式下是好的

**Comment by way-jm** [comment]
直接拉代码build的，未做任何更改，开发模式下ok,均正常，

**Comment by hyrious** [comment]
@BlackHole1

**Comment by way-jm** [comment]
build的时候，把控制台打开，
![image](https://user-images.githubusercontent.com/18083432/150301485-ca9fd1ee-8718-4369-866b-d1c2c4f1a8ac.png)
![image](https://user-images.githubusercontent.com/18083432/150301603-892e2f13-1af2-4feb-a171-71e291e72b40.png)

**Comment by BlackHole1** [comment]
Do you have `xcode` installed on your computer?

**Comment by way-jm** [comment]
> 



> Do you have `xcode` installed on your computer?

No，I didn't ,let me try
