### ISSUE TITLE
Share Screen 

### ISSUE THREAD

**Issue by Michaux-Technology** [netless-io/flat#1348]
Hello, 

Your project is very nice...
I've used it on your server and the Share Screen seems not working. 
I have not Fehler but I see nothing. 

Thanks, 
Bye,

**Comment by Michaux5** [comment]
Hello, 
Sorry I did an Error. It works well
Thanks,

**Comment by Michaux-Technology** [comment]
Sorry I#ve made an Error. 
It works well
