### ISSUE TITLE
[BUG]: share screen not working

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#1592]
Hello, I love what you did on the agora virtual classroom. It's so simple and clean ASF but I noticed an issue during when you click on screen-sharing, the app doesn't do anything as regards to that but it will still show sharing in progress. I guess that this is a bug or something?

_Originally posted by @Tolzy in https://github.com/netless-io/flat/issues/926#issuecomment-1169876747_

**Comment by BlackHole1** [comment]
It looks like this is a bug, can you provide a reproduction process? @Tolzy

**Comment by Tolzy** [comment]
> It looks like this is a bug, can you provide a reproduction process? @Tolzy

Geez, I'm quite busy rn. I just noticed it and that was why informed you about the bug issue.

**Comment by Leooeloel** [comment]
Thanks for the feedback, we will fix this problem in the next version.
