### ISSUE TITLE
[Bug] The eraser would erase images on iOS while it doesn't have such behavior on the other client.

### ISSUE THREAD

**Issue by memset0** [netless-io/flat#1614]
#### Bug description

The eraser tool would erase images on iOS while it doesn't have such behavior on other clients.

#### Excepted behavior

Only the notes on the image shall be erased by the eraser tool.

> This is an issue about iOS client, with no issue in [@netless-io/flat-iOS](https://github.com/netless-io/flat-iOS), I think I should probably issue it in this repo.

**Comment by memset0** [comment]
By the way, after 1) erasing an image and 2) undoing, it would be brought to the top, overwriting other notes.

**Comment by Leooeloel** [comment]
Thanks for the feedback, we will fix this problem in the next version.

**Comment by Leooeloel** [comment]
Hey friend, the problem has been fixed.

**Comment by Leooeloel** [comment]
You can update the version of Flat.
