### ISSUE TITLE
ci: Separate the two building ways between web and desktop client.

### ISSUE THREAD

**Issue by tiyee** [netless-io/flat#1803]
I just want run flat-web, but it spend too much time to run postinstall script of electron.
What makes me angry is that it failed in the end more than 10 minutes later.
I think the electron process is not necessary.

**Comment by hyrious** [comment]
If you're stucked at downloading electron and are in China, you can add this line to .npmrc then try again:

```
ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"
```

(If that does not work, try adding a `v` to the end of the url.)

This is documented in [the zh-CN readme](https://github.com/netless-io/flat/blob/main/docs/readme/README-zh.md#%E6%9E%84%E5%BB%BA%E5%B9%B6%E8%BF%90%E8%A1%8C-flat-electron-%E5%AE%A2%E6%88%B7%E7%AB%AF).

It is not ideal for us to separate the web and electron builds since they share a lot of common codes and dependencies.

You can, for example, remove the desktop package from pnpm-workspace.yaml to exclude it from your local environment.

**Comment by tiyee** [comment]
> If you're stucked at downloading electron and are in China, you can add this line to .npmrc then try again:
> 
> ```
> ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"
> ```
> 
> (If that does not work, try adding a `v` to the end of the url.)
> 
> This is documented in [the zh-CN readme](https://github.com/netless-io/flat/blob/main/docs/readme/README-zh.md#%E6%9E%84%E5%BB%BA%E5%B9%B6%E8%BF%90%E8%A1%8C-flat-electron-%E5%AE%A2%E6%88%B7%E7%AB%AF).
> 
> It is not ideal for us to separate the web and electron builds since they share a lot of common codes and dependencies.
> 
> You can, for example, remove the desktop package from pnpm-workspace.yaml to exclude it from your local environment.

not only electron ,but also `agora-electron-sdk@3.7.0-build.527`

```
.../agora-rtc/agora-rtc-electron postinstall$ pnpm _download:agora-addon
[7 lines collapsed]
│     at module.exports (/home/tiyee/flat/node_modules/.pnpm/agora-electron-sdk@3.7.0-build.527/node_modules/agora-electron-sdk/scripts/genOS.js:9:5)
│     at module.exports (/home/tiyee/flat/node_modules/.pnpm/agora-electron-sdk@3.7.0-build.527/node_modules/agora-electron-sdk/scripts/download.js:21:70)
│     at Object.<anonymous> (/home/tiyee/flat/service-providers/agora-rtc/agora-rtc-electron/scripts/download-agora-addon/patch-download.js:19:1)
│     at Module._compile (node:internal/modules/cjs/loader:1159:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
│     at Module.load (node:internal/modules/cjs/loader:1037:32)
│     at Module._load (node:internal/modules/cjs/loader:878:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
│     at node:internal/main/run_main_module:23:47
│ Node.js v18.12.1
└─ Done in 815ms
Done in 3.2s
```

**Comment by hyrious** [comment]
I managed to run Flat without the electron part locally (that is to say, without the dependency of electron and agora-electron-sdk). Here's the steps:

1. delete `- "desktop/**"` in pnpm-workspace.yaml
2. `rm -rf desktop service-providers/agora-rtc/agora-rtc-electron`

So I'll close this issue as "Completed". Feel free to re-open this issue if you found steps above not work for you.
