### ISSUE TITLE
Can I install this app in HarmonyOS?

### ISSUE THREAD

**Issue by moooofly** [netless-io/flat#1860]
Based on https://flat.whiteboard.agora.io/#download , I find no suitable app to install.

BTW, I don't want to use it from web only.

**Comment by hyrious** [comment]
Sorry but none of our team members know how to developing HarmonyOS apps. I guess it is able to run android app? You can try to download the apk in that case.

**Comment by leavesster** [comment]
I think after reading [Can-harmony-OS-run-Android-apps](https://consumer.huawei.com/za/community/details/Can-harmony-OS-run-Android-apps/topicId_147728/), you will find the answer.
