### ISSUE TITLE
如何自定义主题和UI？

### ISSUE THREAD

**Issue by qimingzizeinan** [netless-io/flat#1873]
例如说修改课中的教具的主题和UI？

**Comment by hyrious** [comment]
如果你是准备二次开发 Flat：Flat 里的组件基本都和业务解耦，可以直接使用 storybook 修改。Fastboard 的默认组件推荐用 CSS 覆盖的方式修改或完全隐藏后自己实现。

如果是以用户身份，希望定制自己的使用体验，目前没有增加除了暗黑模式以外更多主题的计划。

**Comment by qimingzizeinan** [comment]
> 如果你是准备二次开发 Flat：Flat 里的组件基本都和业务解耦，可以直接使用 storybook 修改。Fastboard 的默认组件推荐用 CSS 覆盖的方式修改或完全隐藏后自己实现。
> 
> 如果是以用户身份，希望定制自己的使用体验，目前没有增加除了暗黑模式以外更多主题的计划。

谢谢。
