### ISSUE TITLE
回放页面无法监听到当前播放时间进度

### ISSUE THREAD

**Issue by qimingzizeinan** [netless-io/flat#1903]
在回放页面，进度条是没有办法随着播放向前走的。测试了之后发现：
syncPlayer.on("timeupdate", updateCurrentTime);
这个回调一直没有触发。

**Comment by hyrious** [comment]
有可能是因为该片段没有录 RTC (上方视频)，即这次录制过程中没有任何人打开摄像头或麦克风。当这个视频片段不存在时，syncPlayer 没有办法同步或者说同步进度一直是 0。目前属于已知问题，但是没有好的解决思路。

**Comment by qimingzizeinan** [comment]
好的。正好有另一个问题。我在bigClass页面的使用过程中发现，点击答题器，学生有的时候点击了提交，老师那面看不到学生的提交。

**Comment by Leooeloel** [comment]
目前需要老师给学生开放操作白板的权限，学生才可以正常点击答题器进行提交。请检查是否给学生开放白板权限。

**Comment by qimingzizeinan** [comment]
非常感谢。
