### ISSUE TITLE
Ipad不支持屏幕共享吗

### ISSUE THREAD

**Issue by Hikaruii** [netless-io/flat#1906]
Ipad不支持屏幕共享吗

**Comment by hyrious** [comment]
@vince-hz

**Comment by vince-hz** [comment]
不支持。因为作为教学工具，iPad共享屏幕的使用场景较少。

**Comment by Hikaruii** [comment]
> 不支持。因为作为教学工具，iPad共享屏幕的使用场景较少。

好的谢谢，想找一个用ipad板书教学一对一的软件太难了555，钉钉延迟和画质都太差

**Comment by vince-hz** [comment]
> > 不支持。因为作为教学工具，iPad共享屏幕的使用场景较少。
> 
> 
> 
> 好的谢谢，想找一个用ipad板书教学一对一的软件太难了555，钉钉延迟和画质都太差

Flat 内置的画笔工具不太满意吗？

**Comment by Hikaruii** [comment]
> 

因为用goodnotes讲义配合更方便一些欸

**Comment by vince-hz** [comment]
> > 
> 
> 
> 
> 因为用goodnotes讲义配合更方便一些欸

学生也用iOS的话，你可以试试 Facetime 的同播共享。 Flat 的屏幕共享我们会考虑的，但没那么快。

**Comment by Hikaruii** [comment]
> > > 
> > 
> > 
> > 因为用goodnotes讲义配合更方便一些欸
> 
> 学生也用iOS的话，你可以试试 Facetime 的同播共享。 Flat 的屏幕共享我们会考虑的，但没那么快。

谢谢十分感谢
