### ISSUE TITLE
进入房间后开启录制，结束后回放的后半段是白屏。

### ISSUE THREAD

**Issue by qimingzizeinan** [netless-io/flat#1941]
在使用的过程中，先进入课程，然后打开录制功能。
录制的时间约为四十秒左右。点击结束课程。
去查看回放的时候发现基本正常，但是分享出去从请求中找到.m3u8的链接，查看视频总时长就显示一分钟以上。
在回到electron的客户端查看回放。发现回放总时长也变成了一分多钟了。而可播放的时间只有40秒。

**Comment by Leooeloel** [comment]
很抱歉给你带来糟糕的使用体验，方便的话可以把房间信息发送到 flat@agora.io，我们检查一下，我们会持续的优化产品使用体验，感谢反馈。

**Comment by qimingzizeinan** [comment]
在网页的版本中会存在这个问题。我已向邮箱中发送了一封邮件。邮件标题: 关于github 中提交的issue邮件。issue标题: 进入房间后开启录制，结束后回放的后半段是白屏。

**Comment by hyrious** [comment]
目前使用的回放播放器 (https://github.com/netless-io/sync-player) 会使用真实视频源的时间 (白板时间和服务器记录的一致；RTC 录制由这个录制服务自己管理，可能会产生更长范围的视频），因此你会看到右下角的播放器时长和真实能播的时长不一致。但是实际录制数据是没有丢失的，不影响正常使用。

后面有时间会修复一下。

**Comment by qimingzizeinan** [comment]
目前获取到的事RTC的时间，而不是白板时间？我现在如果想修正这个问题，能否获取到白板时间之后自己去设置时间呢？

**Comment by hyrious** [comment]
你可以自行实现这个播放器逻辑而不用 sync-player。

**Comment by qimingzizeinan** [comment]
非常感谢。
