### ISSUE TITLE
Run pnpm i failed.

### ISSUE THREAD

**Issue by carli-cmnt** [netless-io/flat#1949]
Scope: all 23 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2368
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2368, reused 2356, downloaded 0, added 0, done
node_modules/.pnpm/electron@12.0.15/node_modules/electron: Running postinstall script, failed in 2m 10.3s
.../node_modules/electron postinstall$ node install.js
│ RequestError: socket hang up
│     at ClientRequest.<anonymous> (/home/apps/flat/flat/node_modules/.pnpm/got@9.6.0/node
│     at Object.onceWrapper (node:events:646:26)
│     at ClientRequest.emit (node:events:538:35)
│     at ClientRequest.origin.emit (/home/apps/flat/flat/node_modules/.pnpm/@szmarczak+htt
│     at TLSSocket.socketOnEnd (node:_http_client:466:9)
│     at TLSSocket.emit (node:events:538:35)
│     at endReadableNT (node:internal/streams/readable:1345:12)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
└─ Failed in 2m 10.3s at /home/apps/flat/flat/node_modules/.pnpm/electron@12.0.15/node_modules/electron
 ELIFECYCLE  Command failed with exit code 1.

**Comment by carli-cmnt** [comment]
Someone could tell me how to deal with this problem?

**Comment by hyrious** [comment]
This means it fails to download electron. You may refer to the zh-cn readme or electron's documentation to setup a npm / pnpm config to download electron from a mirror site.

**Comment by carli-cmnt** [comment]
Thanks. I will try it later.

**Comment by hyrious** [comment]
I'm closing it as it is already answered.
