### ISSUE TITLE
Flat Desktop Client Now Available in Arch User Repository (AUR)

### ISSUE THREAD

**Issue by bob675i** [netless-io/flat#1960]
I'm excited to announce that the Flat Desktop client has been successfully ported to the Arch User Repository (AUR). Arch Linux users can now conveniently install the Flat desktop client directly from the AUR.

The package is available at the following AUR repository link: https://aur.archlinux.org/packages/flat-bin

I want to extend my sincere gratitude to [wuyudi](https://github.com/wuyudi) for his invaluable assistance and guidance throughout the porting process.

The application has been thoroughly tested on Arch Linux and runs smoothly. I suggest adding this information to the Flat client's installation guide to let Arch Linux users know about the availability of the app in the AUR.

If there are any bugs or issues associated with the AUR package, please feel free to report them. I am committed to maintaining the package and addressing any issues promptly.

Thank you for your time and for creating such an excellent application. This contribution will greatly enhance the user experience for Arch Linux users.

**Comment by hyrious** [comment]
Wow, thank you.

Just be curious, I saw the PKGBUILD downloads and runs the .asar from a Windows binary. However we do have a native dependency -- agora-electron-sdk, it loads a node extension which is built only for Windows in that binary. So does it really work? Do you have any problems with turning on the camera and seeing the others?

**Comment by bob675i** [comment]
> Wow, thank you.
> 
> Just be curious, I saw the PKGBUILD downloads and runs the .asar from a Windows binary. However we do have a native dependency -- agora-electron-sdk, it loads a node extension which is built only for Windows in that binary. So does it really work? Do you have any problems with turning on the camera and seeing the others?

Indeed, upon further testing of the Flat Desktop client on Arch Linux, you're correct; I have noticed that the meeting features aren't working properly. This issue has been noted in the comments section of the AUR package page. I apologize for any inconvenience this may cause.

**Comment by hyrious** [comment]
Yep. We may end up all using the web version of RTC plus extra works in [electron](https://www.electronjs.org/docs/latest/api/desktop-capturer) to capture desktops. However currently not.

This native module is also the thing that forbids us using a higher version of electron.

**Comment by bob675i** [comment]
> Yep. We may end up all using the web version of RTC plus extra works in [electron](https://www.electronjs.org/docs/latest/api/desktop-capturer) to capture desktops. However currently not.
> 
> This native module is also the thing that forbids us using a higher version of electron.

Understood, thank you for the clarification.
