### ISSUE TITLE
electron/js2c/renderer_init.js:93 Unable to load preload script:

### ISSUE THREAD

**Issue by tllen** [netless-io/flat#1961]
<img width="958" alt="image" src="https://github.com/netless-io/flat/assets/7759527/5d2af1ab-838f-4cea-8565-fa83ba4f541e">

**Comment by hyrious** [comment]
It looks like you're packing the macOS electron app and it fails to find `/dist/preload.js`. Can you try running

```console
pnpm -F flat build
```

&hellip;in the root of this repo and see if it is successfully creating `desktop/main-app/dist/preload.js` ?

**Comment by tllen** [comment]
> It looks like you're packing the macOS electron app and it fails to find `/dist/preload.js`. Can you try running
> 
> ```
> pnpm -F flat build
> ```
> 
> …in the root of this repo and see if it is successfully creating `desktop/main-app/dist/preload.js` ?

<img width="197" alt="image" src="https://github.com/netless-io/flat/assets/7759527/8ea145ae-1604-4dcc-841d-edde39834a32">
exist preload.js

**Comment by hyrious** [comment]
I guess I know what's wrong here, the `dist/preload.js` is only enabled for non-production builds (i.e. in development only with no packing process):

https://github.com/netless-io/flat/blob/913e34f02188edf44fdc410857e6d73b34b78fe9/desktop/main-app/src/utils/runtime.ts#L28-L31

And of course the build script only has a production build:

https://github.com/netless-io/flat/blob/913e34f02188edf44fdc410857e6d73b34b78fe9/desktop/main-app/package.json#L25

I'm not sure how did you pack in a development environment (i.e. `process.env.NODE_ENV != 'production'`), but this is the case.

**Comment by tllen** [comment]
<img width="1275" alt="image" src="https://github.com/netless-io/flat/assets/7759527/3c4f8c61-99d7-46bd-bcd5-e0f979947d67">


> I guess I know what's wrong here, the `dist/preload.js` is only enabled for non-production builds (i.e. in development only with no packing process):
> 
> https://github.com/netless-io/flat/blob/913e34f02188edf44fdc410857e6d73b34b78fe9/desktop/main-app/src/utils/runtime.ts#L28-L31
> 
> And of course the build script only has a production build:
> 
> https://github.com/netless-io/flat/blob/913e34f02188edf44fdc410857e6d73b34b78fe9/desktop/main-app/package.json#L25
> 
> I'm not sure how did you pack in a development environment (i.e. `process.env.NODE_ENV != 'production'`), but this is the case.

<img width="1275" alt="image" src="https://github.com/netless-io/flat/assets/7759527/8d4d4602-d094-4913-baf8-f4c6d2777394">
development build ok,  Home page Entering the room is a white screen

**Comment by hyrious** [comment]
Of course the build is ok (there's no syntax nor runtime error in the build script). I mean "development" is wrong here, it should use `NODE_ENV=production` in producing the `desktop/main-app/dist/main.js`. You can check that file and see if it contains:

```js
var isDevelopment = false;
var isProduction = true;
```

Any other value here is incorrect.

Also make sure you do not set `FLAT_DEBUG=debug` in your runtime.
