### ISSUE TITLE
Camera blank

### ISSUE THREAD

**Issue by tllen** [netless-io/flat#1963]
Generate mac version, open the camera to detect no reaction, enter the room page without any reaction

**Comment by hyrious** [comment]
Is there any error message shown in the devtools, or the whole app just freezes (no response, even the devtools can not open or can not input)?

**Comment by tllen** [comment]
> Is there any error message shown in the devtools, or the whole app just freezes (no response, even the devtools can not open or can not input)?

node scripts/launch/index.js Run well  ，pnpm  ship:mac  Run camera microphone blank

**Comment by hyrious** [comment]
Maybe you just didn't give camera permission to the shipped app.

**Comment by tllen** [comment]
> 

There is no prompt permission to open the program, how do I need to operate
