### ISSUE TITLE
UPDATE_DOMAIN检查版本更新， 阿里云上怎么存放Windows 与 Mac 安装包格式

### ISSUE THREAD

**Issue by tllen** [netless-io/flat#2033]
能有具体例子最好

**Comment by hyrious** [comment]
Electron Updater 会检查这两个文件：

https://flat-storage.oss-accelerate.aliyuncs.com/versions/latest/stable/win/latest.yml

https://flat-storage.oss-accelerate.aliyuncs.com/versions/latest/stable/mac/latest-mac.yml

然后直接去旁边（同目录）找对应文件名的文件。

请参考上传脚本 https://github.com/netless-io/flat/blob/main/scripts/deployment/upload-ali-oss.js
