### ISSUE TITLE
Why phone number required? 

### ISSUE THREAD

**Issue by thomas-rhong** [netless-io/flat#2040]
I don't think it is nessasary.

**Comment by syt-honey** [comment]
> I don't think it is nessasary.

Are you talking about the domestic version?

As you can see, there are two versions available for Flat: one that requires phone number/binding and another that does not.

Based on [Chinese privacy](http://politics.people.com.cn/n1/2017/0825/c1001-29494919.html), a real-name system is necessary for all users. So, when you use the domestic version, no matter which method you use to register, a phone number is required (of course, there are other real-name authentication methods, and Flat currently chooses the mobile phone number).
