### ISSUE TITLE
课堂开启录制报错，麻烦看一下

### ISSUE THREAD

**Issue by tllen** [netless-io/flat#2041]
<img width="684" alt="a1" src="https://github.com/netless-io/flat/assets/7759527/59d232ae-59ac-4d3f-b5e0-275bb86f461b">

服务配置已开启，阿里云配置没有问题

**Comment by hyrious** [comment]
100002 通常是由于后端报错（也就是并非业务逻辑错误，而是 JS 运行时有一个 Error 没有捕捉到）产生的。你可以查看后端的日志（通常在 src/log 或 dist/log）来找到具体错误。

需要注意的是，Agora 的录制服务要求房间内至少存在一路流（就是至少有一个人开了摄像头或麦克风），否则无法录制。
