### ISSUE TITLE
Both chrome and edge browsers on Android don't work.

### ISSUE THREAD

**Issue by BOKE2014** [netless-io/flat#2054]
Both chrome and edge browsers on Android don't work.

**Comment by BOKE2014** [comment]
Both chrome and edge browsers don't work on iOS and iPadOS either.

**Comment by syt-honey** [comment]
> Both chrome and edge browsers don't work on iOS and iPadOS either.

Please offer more information about your problem. Such as, What did you write? What have you got? About what? It is best to provide pictures or code snippets to illustrate your problem.

**Comment by BOKE2014** [comment]
> > Both chrome and edge browsers don't work on iOS and iPadOS either.
> 
> Please offer more information about your problem. Such as, What did you write? What have you got? About what? It is best to provide pictures or code snippets to illustrate your problem.

For security concerns, we are not allowed to download and install apps. Through testing, it has been found that joining or starting meetings is not possible using the Chrome and Edge browsers on Android devices, iPhones, and iPads.

**Comment by syt-honey** [comment]
> > > Both chrome and edge browsers don't work on iOS and iPadOS either.
> > 
> > 
> > Please offer more information about your problem. Such as, What did you write? What have you got? About what? It is best to provide pictures or code snippets to illustrate your problem.
> 
> For security concerns, we are not allowed to download and install apps. Through testing, it has been found that joining or starting meetings is not possible using the Chrome and Edge browsers on Android devices, iPhones, and iPads.

you can join room in browsers by the following steps: 
1. let users login to the application
2. click the 'Join' button
3.  enter the room number to join the room

In fact, Flat did not do mobile browser adaptations. So, even if you've opened it, you may have some challenges. We recommend that users install the app.

**Comment by BOKE2014** [comment]
> > > > Both chrome and edge browsers don't work on iOS and iPadOS either.
> > > 
> > > 
> > > Please offer more information about your problem. Such as, What did you write? What have you got? About what? It is best to provide pictures or code snippets to illustrate your problem.
> > 
> > 
> > For security concerns, we are not allowed to download and install apps. Through testing, it has been found that joining or starting meetings is not possible using the Chrome and Edge browsers on Android devices, iPhones, and iPads.
> 
> you can join room in browsers by the following steps:
> 
> 1. let users login to the application
> 2. click the 'Join' button
> 3. enter the room number to join the room
> 
> In fact, Flat did not do mobile browser adaptations. So, even if you've opened it, you may have some challenges. We recommend that users install the app.

Thanks a lot!
