### ISSUE TITLE
Is it possible to make hyperlinks in Word, PDF, PPT and Excel clickable?

### ISSUE THREAD

**Issue by BOKE2014** [netless-io/flat#2084]
<img width="1280" alt="截屏2023-11-13 16 41 39" src="https://github.com/netless-io/flat/assets/35056286/d7eb23c6-98ec-4867-8702-7b5cac0ab74e">

**Comment by Horan-Ding** [comment]
Except for dynamic PPT, it is not possible to implement click-to-jump in other files(PDF, Word, Excel). In PPT, we consider it unsafe to jump to other links, so we have not implemented this feature.
