### ISSUE TITLE
Can I use it in the vue system built by npm?

### ISSUE THREAD

**Issue by iFence** [netless-io/flat#2103]
Can I use flat in the vue system built by npm?

I don't understand the use of pnpm，and my front-end project is developed with vue and built using npm,can I integrate this project into my system?

**Comment by hyrious** [comment]
Not very straightforward. As you may know Flat is an **application**, not a library. Flat's UI part is built on top of React. The rest of the application are [services](https://github.com/netless-io/flat/tree/main/service-providers) (like WebRTC and whiteboard) which are usually independent with each other.

So if you want to re-use the UI part of Flat, there's no easy way to integrate the [React components](https://github.com/netless-io/flat/tree/main/packages/flat-components) in a Vue framework. If you only want the whiteboard part, Flat is using [Fastboard](https://github.com/netless-io/fastboard) which can be easily integrated in any framework.

If you want to re-use the services of Flat (mostly wrappers around libraries provided by Agora), there's no block for you to access the [services](https://github.com/netless-io/flat/tree/main/service-providers).

**Comment by iFence** [comment]
I see, thank you.
