### ISSUE TITLE
cannot resolve https://npmmirror.com/mirrors/electron/12.0.15/electron-v12.0.15-win32-x64.zip: status code 404

### ISSUE THREAD

**Issue by jingjingding** [netless-io/flat#2125]
cannot resolve https://npmmirror.com/mirrors/electron/12.0.15/electron-v12.0.15-win32-x64.zip: status code 404

**Comment by hyrious** [comment]
That was because npmmirror needs <code>.../electron/<ins>v</ins>12.0.15/electron-v...</code> in electron 12 and before.

You can set your `ELECTRON_MIRROR` with this env and try again:

```bash
export ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/v"
```
