### ISSUE TITLE
How can I create an account using a Google email when that part is missing from your frontend?

### ISSUE THREAD

**Issue by zerohct** [netless-io/flat#2145]
i see your code have user_google, user_apple, ...  
![image](https://github.com/netless-io/flat/assets/100672288/4f156297-bc4a-4846-b132-ebf6f3c7c15c)
Why does it disappear in the frontend?
![image](https://github.com/netless-io/flat/assets/100672288/f0626338-bd96-4f96-9819-7a057fbfe725)
 Where can I edit it to be able to create an account using a Google email?
Thanks.

**Comment by hyrious** [comment]
The login methods is configured at https://github.com/netless-io/flat/blob/main/config/SG/.env.production named `LOGIN_METHODS`. Only the SG version has google account login method. You can change the config to enable it.

**Comment by zerohct** [comment]
Is there a way to log in without using OAuth authentication?

**Comment by hyrious** [comment]
Flat does have phone-password and email-password methods to login to the account. They do not require OAuth. However the CN version of Flat requires the phone number to be registered due to the law of the country.

**Comment by zerohct** [comment]
thanks
