### ISSUE TITLE
screenshots, and tools

### ISSUE THREAD

**Issue by GTech08** [netless-io/flat#2152]
I really appreciate Flat App since it's free, and easier to use. However, I noticed that you can't take a screenshot from a separate browser or from within the classroom interface. There is no color white nor black when using the pen tool too. Please check, and add these features. Thank you.

**Comment by Leooeloel** [comment]
Adding a screenshot tool to the software will result in a bulky package, we recommend using the system's own screenshot shortcuts (or your familiar screenshot method) to complete the screenshot, and then paste the image, drag and drop the image to place it into the whiteboard for display.

Later versions of flat will support user-defined brush colors, the exact timing of the update is still uncertain. We can be contacted by email at flat@agora.io

**Comment by GTech08** [comment]
Thank you, Leo.
    On Thursday, July 4, 2024 at 06:57:13 PM GMT+8, Leo ***@***.***> wrote:  
 
 


Adding a screenshot tool to the software will result in a bulky package, we recommend using the system's own screenshot shortcuts (or your familiar screenshot method) to complete the screenshot, and then paste the image, drag and drop the image to place it into the whiteboard for display.

Later versions of flat will support user-defined brush colors, the exact timing of the update is still uncertain. We can be contacted by email at ***@***.***
