### ISSUE TITLE
添加邮箱登陆

### ISSUE THREAD

**Issue by Makitoid** [netless-io/flat#2162]
有时候github会连接不上，在学校又没手机收验证码。。。

**Comment by hyrious** [comment]
I think it is ok if the bound phone was verified @Leooeloel.

**Comment by Leooeloel** [comment]
是的，可以使用邮箱、密码注册登录（首次注册需要绑定手机号）

**Comment by Makitoid** [comment]
也就是说，无论如何都得绑定手机号（即使邮箱，微信这些都绑定了手机号）？

**Comment by Leooeloel** [comment]
是的，这是国内实名政策要求，必须绑定手机号
