### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by YiwenZoe** [netless-io/flat#569]
Environment: Mac Big Sur
Node: v16.0.0
NPM: v7.10.0
Yarn: v1.22.10

and 

Environment: Windows 10
Node: v14.15.4
NPM: v6.14.10
Yarn: v1.22.10

```
yiwen@YIWENtekiMacBook-Pro flat % yarn install --frozen-lockfile
yarn install v1.22.10
$ node ./scripts/preinstall
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Couldn't find match for "fb67b54fe18bdf556fb3e3d00db5fbaf0dbb294d" in "refs/heads/dependabot/npm_and_yarn/electron-9.4.0,refs/heads/dependabot/npm_and_yarn/ini-1.3.8,refs/heads/dependabot/npm_and_yarn/lodash-4.17.19,refs/heads/dependabot/npm_and_yarn/npm-6.14.6,refs/heads/dependabot/npm_and_yarn/npm-registry-fetch-4.0.5,refs/heads/dependabot/npm_and_yarn/npm-user-validate-1.0.1,refs/heads/fix-electron-warning,refs/heads/master,refs/tags/v1.0.0,refs/tags/v1.0.1,refs/tags/v1.0.2,refs/tags/v1.0.3,refs/tags/v1.0.4,refs/tags/v1.0.5,refs/tags/v1.1.0,refs/tags/v1.1.1,refs/tags/v1.1.2,refs/tags/v1.1.3,refs/tags/v1.1.4,refs/tags/v1.1.5,refs/tags/v2.0.0,refs/tags/v2.0.1,refs/tags/v2.1.0,refs/tags/v2.2.0,refs/tags/v2.2.1,refs/tags/v2.2.2,refs/tags/v2.2.3,refs/tags/v2.2.4,refs/tags/v3.0.0,refs/tags/v3.1.0,refs/tags/v3.1.1" for "git://github.com/BlackHole1/electron-devtools-installer".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by BlackHole1** [comment]
try: `(rm -rf node_modules ./**/node_modules || true) && yarn install --force --frozen-lockfile`

I did not reproduce this problem locally

make sure that you are executing `yarn install --force --frozen-lockfile` in the root directory of the flat project

At the same time, we need to confirm that `main-app -> package.json -> electron-devtools-installer` value is: `git://github.com/BlackHole1/electron-devtools-installer#fb67b54fe18bdf556fb3e3d00db5fbaf0dbb294d`

If none of the above steps can be recovered, please make sure that your network is normal and the terminal had better start the agent.

**Comment by BlackHole1** [comment]
@YiwenZoe  This issue has been resolved and the related PR is available at: https://github.com/netless-io/flat/pull/621
