### ISSUE TITLE
control scale api

### ISSUE THREAD

**Issue by wu0211** [netless-io/flat#700]
Did you solve the problem of controlling scaling API mentioned before

**Comment by wu0211** [comment]
Disable Scale

**Comment by crimx** [comment]
Hi thanks for your feedback. Could you provide the full context of your issue?

**Comment by wu0211** [comment]
> Hi thanks for your feedback. Could you provide the full context of your issue?

When I upload PPF to whiteboard,I might want to disable zoom or  whiteboard move

**Comment by crimx** [comment]
Remove the [`room.scalePptToFit()`](https://github.com/netless-io/flat/blob/599e04f6ececd1312cca71e42d4569c20c431dba/desktop/renderer-app/src/pages/CloudStoragePage/index.tsx#L194) after injecting PDF or PPT to Whiteboard.

**Comment by Leooeloel** [comment]
If you have any other questions, please feel free to add my WeChat and I invite you to join the Flat open source project exchange group. My WeChat is: 18860379049
