### ISSUE TITLE
[refactor]: remove Chinese comment

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#712]
remove all Chinese comment in project, replace with English.

Because this project is open to all developers worldwide, we should use English as the primary language for ease of communication and maintenance

match Regex: `(//|\* ).*[\u4e00-\u9fa5]`
file type: `*.ts,*.tsx,*.json,*.js.`

e.g:
<img width="879" alt="图片" src="https://user-images.githubusercontent.com/8198408/120919538-bcf9c880-c6ec-11eb-93cb-6ded535e8504.png">

**Comment by Patil2099** [comment]
I would love to pick this up.

**Comment by BlackHole1** [comment]
> I would love to pick this up.

cool. we very much welcome

**Comment by BlackHole1** [comment]
@Patil2099 are you still doing this?

if there is a problem, we can help.

**Comment by facinick** [comment]
Hey, how are we supposed to replace it with english, asin what translate service to use? google translate?

**Comment by BlackHole1** [comment]
> Hey, how are we supposed to replace it with english, asin what translate service to use? google translate?

google or deepl or other translation services, use what you think is right and we will assist you in the review
