### ISSUE TITLE
Pause room status can't resume

### ISSUE THREAD

**Issue by outman** [netless-io/flat#757]
After click pause button, resume not working.

**Comment by Leooeloel** [comment]
> After click pause button, resume not working.

Thanks for the feedback, we will fix this issue in the near future. 

We would be happy to communicate with you further to understand and help you solve the problems you encountered while using Flat, please leave your contact information, such as WeChat, if convenient, and I will add you as a friend.

**Comment by BlackHole1** [comment]
We will recently reproduce the problem, and if it exists, we will fix it as soon as possible

**Comment by Leooeloel** [comment]
> After click pause button, resume not working.

Thank you for your feedback. Currently, when you click the Pause Class button, the teacher's audio/video is automatically turned off, and when you click the Resume Class button, the teacher's audio/video is not restored properly, we will fix this problem in the near future.
