### ISSUE TITLE
[bug]: resolve load source-map error

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#804]
## Reproduce Step

1. open flat
2. open devtools at `renderer`
3. switch `console`
4. (option) click WeChat Login button:
   <img width="1163" alt="图片" src="https://user-images.githubusercontent.com/8198408/126442512-7469e122-5282-42af-b5f3-81cb04a74c98.png">

## Note

launch `Flat` when development environment:
<img width="1129" alt="图片" src="https://user-images.githubusercontent.com/8198408/126440670-818b5095-4883-4e85-bd90-d46b1898363d.png">

if click weChat Login button:
<img width="1110" alt="图片" src="https://user-images.githubusercontent.com/8198408/126441711-8a3584fa-79e7-453d-ae1b-397bcc4c84b4.png">

----

if open the release `Flat`:
<img width="554" alt="图片" src="https://user-images.githubusercontent.com/8198408/126441315-3cdc4163-c725-44d9-b411-dbda34e09853.png">

if click weChat Login button:
<img width="795" alt="图片" src="https://user-images.githubusercontent.com/8198408/126441772-e181ea77-1e19-4d5f-ac92-2c7a76ad7e78.png">

**Comment by yamasite** [comment]
## Solution

Just had some time to check this issue and found a similar reported issue here:
https://github.com/electron/electron/issues/22996#issuecomment-720893684

This is an issue with Electron, which incorrectly resolves the sourceMappingURL generated by Webpack devtool. So, you need to correct the path.

## Steps

### Option1: Update preload.js

If you update the following code in `preload.js`

```ts
//# sourceMappingURL=preload.js.map
```

with

```ts
//# sourceMappingURL=file:///location/to/preload.js.map
```

The issue will go away. This applies to both dev and prod.

![image](https://user-images.githubusercontent.com/10089260/132490831-d9795e0b-2312-402a-a353-8c8afae99bc3.png)

### Option 2: Update webpack.common.js

Add `devtoolModuleFilenameTemplate` to `webpack.common.js`:

```ts
module.exports = {
  //...
  output: {
    ...
    devtoolModuleFilenameTemplate:
      'file:///[absolute-resource-path]',
  },
};
```

The warning will also go away.

**Comment by yamasite** [comment]
See https://github.com/netless-io/flat/pull/938 for the fix.

**Comment by BlackHole1** [comment]
Thanks for the PR!

**Comment by BlackHole1** [comment]
I will test it tomorrow. Everything seems to be fine so far
