### ISSUE TITLE
[refactor]: `INVITE_BASEURL` does not meet the semantics in flat-web

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#830]
`INVITE_BASEURL` Does not meet the semantics

_Originally posted by @BlackHole1 in https://github.com/netless-io/flat/pull/829#discussion_r679042876_

https://github.com/netless-io/flat/pull/834/files#diff-80cd6ff40d48acb0207a9e0780233787449517800f219c43a5d83f1569b344d1R95

**Comment by BlackHole1** [comment]
`INVITE_BASEURL` => `WEB_DOMAIN`

**Comment by LitoMore** [comment]
Not sure we support `https://example.com/SUB_DIRECTORY/replay/ROOM_TYPE/ROOM_UUID/OWNER_UUID/` kind of link or not.

If we want to support this kind of URL, we should not name it to the `domain`. `base_url` is better.

BTW, I noticed we already have the constant `FLAT_WEB_DOMAIN` in https://github.com/netless-io/flat/blob/main/web/flat-web/src/constants/process.ts.

Use `INVITATION_BASE_URL` or `INVITATION_ENDPOINT` instead will be better, IMO.

**Comment by BlackHole1** [comment]
In https://github.com/netless-io/flat/pull/829, our requirement is to open the replay link, so using `INVITATION`/`INVITE`  is not a good idea in this scenario.

This is because `INVITE_BASEURL` and `FLAT_WEB_DOMAIN` have a certain overlap.
Their domain names must be the same

see:

https://github.com/netless-io/flat/blob/a19b6be34d36d9c0aed1bd672d28cb1da6e121a2/config/.env.development#L12-L14

cc @LitoMore

**Comment by BlackHole1** [comment]
Should we only keep `FLAT_WEB_DOMAIN`? Or, keep `FLAT_WEB_DOMAIN` and give it a better name, e.g: `WEB_DOMAIN`?

**Comment by LitoMore** [comment]
The link `https://{DOMAIN}` with a protocol (`https:`) called URL or endpoint.

It's OK to use `domain` if it does not have the protocol part.

You could try this in Node.js REPL:

```js
> new URL('https://exmaple.com:8080/test/test/file.ext')
```

The result will be:

```js
URL {
  href: 'https://exmaple.com:8080/test/test/file.ext',
  origin: 'https://exmaple.com:8080',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'exmaple.com:8080',
  hostname: 'exmaple.com',
  port: '8080',
  pathname: '/test/test/file.ext',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

The `domain` and the `hostname` are the same thing. Hope this helps you understand the URL.

**Comment by BlackHole1** [comment]
Thanks for the correction, that might be better called `FLAT_WEB_ORIGIN` / `FLAT_WEB_URL` / `FLAT_WEB_BASE_URL`?

**Comment by LitoMore** [comment]
The `WEB_URL` sounds like a full URL. `Origin` is only used for the HTTP regions, it's not a good choice for URL naming.

`FALT_WEB_BASE_URL` looks good.

**Comment by BlackHole1** [comment]
Good. Would anyone like to try and submit a PR for this issue? @netless-io/developers

**Comment by LitoMore** [comment]
OK, let me solve this.
