### ISSUE TITLE
[pref]: refactor date-fns import/use

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#854]
In the project, I found that we were mixing up the data-fns approach, which would result in less maintainable code and no `Tree shaking`, eg:

```ts
import { format } from "data-fns/fp";
import { add } from "data-fns";
import max from "data-fns/max"
```

After testing, I found that I should change the data-fns to:

```ts
import format from "date-fns/fp/format";
import addBusinessDays from "date-fns/fp/addBusinessDays";
```

### **we should use `fp`, unless the method does not exist in `fp`**
> This is for code maintainability reasons

----

I tested several different writing methods to analyze their final pack size

## mix use `deconstruction`

```ts
import { format } from "date-fns";
import { addBusinessDays } from "date-fns/fp";
```

**Stat Size: `625.18 KB`**

<img width="1022" alt="图片" src="https://user-images.githubusercontent.com/8198408/128798538-b3d010cb-a0f5-42fb-8bca-282e9ff2c3a7.png">

## use `deconstruction`

```ts
import { format } from "date-fns/fp";
import { addBusinessDays } from "date-fns/fp";
```

**Stat Size: `582.38 KB`**

<img width="1486" alt="图片" src="https://user-images.githubusercontent.com/8198408/128798713-26d01ad4-b504-429b-8887-3cb0fadda3e8.png">

## mix use `no deconstruction` 

```ts
import format from "date-fns/format";
import addBusinessDays from "date-fns/fp/addBusinessDays";
```

**Stat Size: `91.98 KB`**

<img width="736" alt="图片" src="https://user-images.githubusercontent.com/8198408/128799115-249016e8-a340-4d21-bbd7-733e065a70af.png">

## use `no deconstruction` 

```ts
import format from "date-fns/fp/format";
import addBusinessDays from "date-fns/fp/addBusinessDays";
```

**Stat Size: `92.21 KB`**

<img width="739" alt="图片" src="https://user-images.githubusercontent.com/8198408/128798886-53832ae4-41d8-4ced-8b0a-86bb545188ce.png">

----

From the above, we can see that there is not much difference between `mix use no deconstruction` and `use no deconstruction`. The reason why `use no deconstruction` is a bit larger than `mix use no deconstruction` is that there is more code for fp implementation.

As I mentioned above, we should only use one for code maintainability (usually fp's methods are sufficient for our needs)

Another reason to choose fp is that we can take advantage of `Currying` for further abstraction.

**Comment by hyrious** [comment]
I doubt your webpack config is not tweaked well to do [tree shaking](https://webpack.js.org/guides/tree-shaking/).
I also made some experiment with bundlers:

### Setup

```shell
mkdir test-date-fns && cd test-date-fns
npm init -y
npm i -D date-fns esbuild rollup @rollup/plugin-node-resolve webpack webpack-cli
```
index.js
```js
import { format } from "date-fns";
import { addBusinessDays } from "date-fns/fp";

// `console.log` is required for rollup to mark side effects
console.log(format, addBusinessDays);
```
webpack.config.js 😒 
```js
module.exports = {
    entry: './index.js',
    output: {
        filename: 'bundle.webpack.js',
        path: __dirname,
    },
    mode: 'development',
    devtool: false, // required to make `eval(string)` shorter
    optimization: {
        usedExports: true,
    }
}
```
Let's see:
```
npx esbuild index.js --bundle --outfile=bundle.esbuild.js

  bundle.esbuild.js  51.7kb

Done in 252ms
```

```
npx rollup -i index.js -p node-resolve -o bundle.rollup.js

index.js → bundle.rollup.js...
created bundle.rollup.js in 3.8s
ls bundle.rollup.js
88,941 bundle.rollup.js
```

```
npx webpack
asset bundle.webpack.js 140 KiB [compared for emit] (name: main)
orphan modules 533 KiB [orphan] 467 modules
runtime modules 396 bytes 2 modules
cacheable modules 92.2 KiB
...
```

| file | size | description |
| --- | --- | --- |
| **bundle.esbuild.js** | 51.7kb | esbuild strips comments by default |
| bundle.rollup.js | 88.94kb | - |
| bundle.webpack.js | 140kb | webpack inserts a lot of runtime codes |

The difference is webpack generates a lot of `/* harmony export */` things and esbuild strips comments. In short, they both do tree shaking well.

To make it fair, I also include minified results here (rollup use [terser](https://github.com/TrySound/rollup-plugin-terser) plugin, esbuild use itself):

| file | size |
| --- | --- |
| bundle.esbuild.js | 22,54kb |
| bundle.rollup.js | 21.95kb |
| **bundle.webpack.js** | 21.77kb |

As you can see, they are almost the same.

**Comment by BlackHole1** [comment]
@hyrious 
i will try again in the near future, following your webpack config.
