### ISSUE TITLE
[bug]: autoResize not scaling

### ISSUE THREAD

**Issue by parallelmedical** [netless-io/flat#904]
Im finding that autoresize scaling is not adjusted when adjusting the whiteboard div. Sometimes it works but most of the time it doesn't.

I believe the issue is due to the ApplianceManager.GetViewState() returning 0  for width and 0 for height. When the adaptRectangle is created it forces a scale of 1.

when refreshSize is called this.adaptRectangle is null which forces the resize property to take this.camera property.

is this a race condition as the DIV container is not yet created so the Width and Height is 0?

below is excerpts of white-sdk

creation of adaptRectangle below

```ts
  key: "adaptRectangle",
          value: function adaptRectangle(e) {
              if (e.width === 0 || e.height === 0) this.transformCamera({
                  animationMode: e.animationMode,
                  centerX: e.originX + e.width / 2,
                  centerY: e.originY + e.height / 2,
                  scale: 1
              });
              else {
                  var t = He(D({}, this.cameraWithAdaptRectangle(e, e.adapterMode)), {
                      animationMode: e.animationMode
                  });
                  this.setCameraTransfrom(t, !1), this.adaptedRectangle = Object.freeze({
                      originX: e.originX,
                      originY: e.originY,
                      width: e.width,
                      height: e.height,
                      adapterMode: e.adapterMode
                  })
              }
          }
        },
```

this.adaptedRectangle is null and therefore this.camera properties are taken.

```ts
key: "refreshSize",
        value: function refreshSize(e, t) {
            if (this._width !== e || this._height !== t) {
                this._width = e, this._height = t;
                var r;
                this.adaptedRectangle ? r = this.cameraWithAdaptRectangle(this.adaptedRectangle, this.adaptedRectangle.adapterMode) : r = this.camera, this.setCameraTransfrom(He(D({}, r), {
                    animationMode: G.Immediately
                }), !1), this.dispatchUpdatedEvent(r, !1), this.sizeUpdatedDispatcher.dispatch({
                    width: e,
                    height: t
                })
            }
        }
```

**Comment by BlackHole1** [comment]
Thank you for your feedback, we will be investigating in the near future

**Comment by BlackHole1** [comment]
@Moskize91 Is this expected? Or is this a bug?

If it's a bug, do we have an estimated timeline for fixing it?

**Comment by BlackHole1** [comment]
This is a known whiteboard issue that we will fix in the next release.

The reason is that your browser does not have a `window.ResizeObserver` method

We will fix this issue and release a version that is compatible without `window.ResizeObserver` by next week

**Comment by parallelmedical** [comment]
thanks, ive updated to white-sdk 2.13.19 and it fixed the issue.

**Comment by parallelmedical** [comment]
spoke to soon, seems to be some kind of race condition as its no longer working.

**Comment by BlackHole1** [comment]
> spoke to soon, seems to be some kind of race condition as its no longer working.

Can you elaborate on that?

**Comment by parallelmedical** [comment]
i updated to 2.13.19, reloaded the application, when i entered a room that previously had whiteboard content i was able to grab the window corner and re-size.  the images and drawing re-size appropriately  as-well as the scale percentage update on the netless zoom controller. refresh the page and it no longer works, when i try to re-size the images and drawings move on the canvas to fit but dont reduce in size. ill try and capture some screenshots.

**Comment by BlackHole1** [comment]
ok, it would be nice to have a video

**Comment by parallelmedical** [comment]
sorry for the delay, i have updated the white-sdk and window manager. You can see from the video that both clients when resizing window don't rescale the annotation however after changing the vision control any follower clients scale correctly, is this expected behaviour?

https://vimeo.com/618749466

**Comment by hyrious** [comment]
Yes, it is as expected. The follower side will always be scaled to be able to see full content of the host side when the vision control is turned on.

**Comment by parallelmedical** [comment]
thanks @hyrious, is there a way to always force scaling?

**Comment by hyrious** [comment]
You can call [`room.moveCameraToContain(rect)`](https://developer.netless.link/javascript-en/home/displayer-methods#movecameratocontain) to turn on auto scaling.

**Comment by parallelmedical** [comment]
calling this requires multiviews to be false, then I'm unable to call WindowManager.mount

index.js?c37d:52530 Uncaught (in promise) Error: you can only read views when useMultiViews is true
    at ho.get (index.js?c37d:52530)
    at xe.createMainView (index.es.js?545f:1)
    at new xe (index.es.js?545f:1)
    at new ye (index.es.js?545f:1)
    at Function.mount (index.es.js?545f:1)
    at mountWindowManager (Whiteboard.tsx?6296:116)

**Comment by hyrious** [comment]
`WindowManager.mount()` should be run before calling this method. It is `View.moveCameraToContain()` in fact in multiview. ([source](https://github.com/netless-io/window-manager/blob/35d95b6df1907f091193bebaf82a4f19b0a0c252/src/Utils/RoomHacker.ts#L16))
