### ISSUE TITLE
question(web): run start failed

### ISSUE THREAD

**Issue by sarthak55k** [netless-io/flat#943]
I was working on the flat-web module but eventually got some error
![error](https://user-images.githubusercontent.com/61469620/132703960-bcaefed1-fc7d-4823-9ba1-8dc7c4ae186f.png)

Can anyone suggest how to resolve the error

**Comment by BlackHole1** [comment]
Can you tell us your system information?

and whether you executed `yarn run bootstrap`  in the project root directory, this command will assist you to get your current environment ready.
And whether you got any error while executing `yarn run bootstrap`?

**Comment by sarthak55k** [comment]
yarn run bootstrap is for both desktop application and web application. 
I just want to use web application so when i was running it seperately by using the command: 
tsc src/index.ts 
i was getting the above error.
i tried it on both windows and linux(ubuntu) and both were giving the same error.

if i am getting something wrong, can u tell me the correct way to just use the web module.

**Comment by BlackHole1** [comment]
I probably know what the problem is, because when using `yarn run bootstrap`, we will install agora-electron-sdk, which currently has no linux version. Also we didn't consider the situation under linux development before

Also, you shouldn't use the tsc tool to compile directly. _flat-web_ currently uses the vite build tool. You should use `yarn run start` in the _flat-web_ directory for development


I will get `yarn run bootstrap` to support linux in the following hours (just to make sure can get the process done properly, but still can't develop desktop under linux)

**Comment by hyrious** [comment]
1. Make sure you have `yarn install` (will fail on linux, @BlackHole1 will fix it)
2. `yarn workspace flat-web start`

**Comment by BlackHole1** [comment]
@sarthak55k 

you can now run `yarn run bootstrap`, then run `yarn workspace flat-web start` or `cd web/flat-web && yarn run start`

**Comment by BlackHole1** [comment]
thank you for your feedback.

If there is still a problem, you can comment and we will reopen the issue

**Comment by sarthak55k** [comment]
Still there is a issue 
i guess the issue is in react-virtualized package. 
similar issue is raised at their github repo and they are working on it 
![react-virtualized_err](https://user-images.githubusercontent.com/61469620/132813949-ced872c8-cce0-499f-89b5-924a80af39ae.png)

i tried to comment the import in the node module and it worked 
but thats not the correct way ig

**Comment by BlackHole1** [comment]
@hyrious

**Comment by hyrious** [comment]
@sarthak55k You're right. Currently we just bypass this wrong file with a [postinstall script](https://github.com/netless-io/flat/blob/main/web/flat-web/scripts/react-virtualized.ts) to modify the file like you have done. If for some reason the postinstall script did not run on your machine, you can try to execute `yarn workspace flat-web postinstall` manually.

In other words, what you have done _is the correct way_.

**Comment by sarthak55k** [comment]
yeah its working 
One more thing want to ask 
How to separate the web from the desktop project 
I want to just use the web part
it will be great help

**Comment by BlackHole1** [comment]
At the moment their code is basically separate, you can use/develop the `web` without having to care about the existence of the `desktop`
