### ISSUE TITLE
[BUG]: Better to list iTerm as a prerequisite for macOS developers

### ISSUE THREAD

**Issue by yamasite** [netless-io/flat#963]
macOS developers will encounter a script error when running the project with `yarn run start` if iTerm is not installed. Better to list this as a prerequisite. Otherwise, the startup experience may not smooth for some developers.

**Comment by hyrious** [comment]
Hi, thank you for giving this project a try. We will add this information later.

Also, I still want to know what error did you meet. Currently the [startup script](https://github.com/netless-io/flat/blob/main/scripts/launch/start.scpt) will fallback to use Terminal.app, which is a built-in on macOS, if you don't have iTerm installed. This script just work fine on our machines. Maybe we can make it better by dealing with your error message.

**Comment by yamasite** [comment]
It did not work on my machine. I have to install iTerm to fix this.

![截屏2021-09-19 下午10 35 45](https://user-images.githubusercontent.com/10089260/133931621-e5cbba99-cd0b-44af-b814-afe22034deb9.png)

**Comment by yamasite** [comment]
This error reports on both Catalina and Big Sur.

**Comment by BlackHole1** [comment]
I will fix this problem in the near future
