### ISSUE TITLE
[refactor]: add object-curly-newline rule in eslint

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#966]
To keep the code style uniform, we need this rule

rule details: https://eslint.org/docs/rules/object-curly-newline

You should add this rule to `eslintCommon -> base -> rules` in [.eslint.common.js](https://github.com/netless-io/flat/blob/ef6668bbcb75503b0fb6c502601ec2de910b2df8/.eslint.common.js). eg:

https://github.com/netless-io/flat/blob/ef6668bbcb75503b0fb6c502601ec2de910b2df8/.eslint.common.js#L133-L134

just like this:

<img width="591" alt="图片" src="https://user-images.githubusercontent.com/8198408/134334116-10a86b75-e92d-4152-b41a-cd5b6a94a72a.png">

**Comment by BlackHole1** [comment]
@rbrishabh Would you be interested in looking at this issue?

**Comment by BlackHole1** [comment]
@syt-honey Would you be interested in looking at this issue?

**Comment by syt-honey** [comment]
> @syt-honey Would you be interested in looking at this issue?

yeah, I'll look at this soon.

**Comment by syt-honey** [comment]
@BlackHole1 

Hello, how do you see this configuration?

```js
"object-curly-newline": ["error", {
    "ObjectExpression": "always",
    "ObjectPattern": { "multiline": true, "minProperties": 2 },
    "ImportDeclaration": { "multiline": true, "minProperties": 3 },
    "ExportDeclaration": { "multiline": true, "minProperties": 3 }
}]
```

Excessive use of `always` may have a full screen `space`, but the `never` will reduce readability.

So I adjusted the properties. I'm not sure it's reasonable.

**Comment by BlackHole1** [comment]
The impact of space is something that we probably don't care much about.
What we care more about is consistency of code style

**Comment by syt-honey** [comment]
> The impact of space is something that we probably don't care much about. What we care more about is consistency of code style

Well, the below config will be set later.
```js
"object-curly-newline": ["error", {
      "ObjectExpression": "always",
      "ObjectPattern": { "multiline": true },
      "ImportDeclaration": "never",
      "ExportDeclaration": { "multiline": true, "minProperties": 3 }
}]
```

In addition, I'm confused about why can't make code consistency by my config? Config set in global, and then fix the all of code to format(via command). That's consistency, isn't it?

**Comment by BlackHole1** [comment]
> In addition, I'm confused about why can't make code consistency by my config? Config set in global, and then fix the all of code to format(via command). That's consistency, isn't it?

I don't quite understand what you mean, are you asking how to format the code in a project with a single command?

cc: @syt-honey

**Comment by syt-honey** [comment]
> > In addition, I'm confused about why can't make code consistency by my config? Config set in global, and then fix the all of code to format(via command). That's consistency, isn't it?
> 
> I don't quite understand what you mean, are you asking how to format the code in a project with a single command?
> 
> cc: @syt-honey

nope~, it doesn't matter.

There are multiple conflicts and I'll fix them before submitting my code.

Please wait a moment~
