### ISSUE TITLE
[refactor]: activate terminal after start command 

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat#979]
exec `yarn run start` in project root path, will open system terminal or iTerm2.
but they(terminal / iTerm2) will not to the front (like z-index).

https://user-images.githubusercontent.com/8198408/134791718-c0984784-4dcd-4491-8baf-2a1bf55369e0.mp4

related documents: https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW60

related code: 
* https://github.com/netless-io/flat/blob/63b14ae5ac38a9a9822f1dbdba0da3f6a3d6aa83/scripts/launch/mac/launch_iTerm.scpt#L1-L10

* https://github.com/netless-io/flat/blob/63b14ae5ac38a9a9822f1dbdba0da3f6a3d6aa83/scripts/launch/mac/launch_terminal.scpt#L1-L5

**Comment by BlackHole1** [comment]
@l1shen Would you be interested in looking at this issue?

**Comment by l1shen** [comment]
> @l1shen Would you be interested in looking at this issue?

Okay I'll take a look at it later
