### ISSUE TITLE
[bug]: error was reported after joining the room

### ISSUE THREAD

**Issue by meimosor** [netless-io/flat#996]
![image](https://user-images.githubusercontent.com/31975932/137248043-7f71568a-b02a-47ed-9037-2966ed60414e.png)

**Comment by meimosor** [comment]
![image](https://user-images.githubusercontent.com/31975932/137251607-c5746262-9cf3-451c-b37c-107dc8d50e4b.png)
![image](https://user-images.githubusercontent.com/31975932/137251631-a114daf6-c881-45f4-ab45-b14864ef0739.png)

**Comment by hyrious** [comment]
It seems `rtcEngine` is not defined on desktop app when join the room.
https://github.com/netless-io/flat/blob/26cd62ee2fb0cc81a79cc3b6d8564edfda79cf7b/desktop/renderer-app/src/apiMiddleware/Rtc.ts#L29-L31

I didn't reproduce this error on my machine. @BlackHole1 can you investigate it?

**Comment by BlackHole1** [comment]
@meimosor Have you refreshed your classroom page?

**Comment by meimosor** [comment]
> @meimosor Have you refreshed your classroom page?

No, as long as you click to join the room, this error will be reported immediately

**Comment by BlackHole1** [comment]
did you launch it in a development environment, or did you use our built application?

**Comment by meimosor** [comment]
> did you launch it in a development environment, or did you use our built application?

I pulled the main branch source code directly to run, launch it in a development environment.

**Comment by BlackHole1** [comment]
I think I know the problem, under windows we can only use 32-bit nodejs, because agora-electron-sdk doesn't support 64-bit nodejs

Please try using:

```shell
nvm install 16.4.1 32
nvm use 16.4.1 32
yarn run bootstrap
```

> When running these commands, remember to synchronize the most recent code

**Comment by hyrious** [comment]
> because agora-electron-sdk doesn't support 64-bit nodejs

Not exactly, currently it uses the latest agora sdk and x64 for both macos and windows OS.

**Comment by BlackHole1** [comment]
We are still using 32-bit instead of 64-bit in our project. Because I have not received any news that it supports 64-bit

see:

https://github.com/netless-io/flat/blob/dd1069e5c9e6f74f4dd84b30eda85285dfaa679a/scripts/init-agora-configure/agora-electron-options.js#L3

**Comment by meimosor** [comment]
Well, I run it in a 64-bit environment. Another question is, where is the document address of the project? If I want to run on the web, which project should I pull and what are the steps?

**Comment by BlackHole1** [comment]
we are still in the stage of refining the project and do not have particularly much time to write the documentation.

The backend currently used in this project is also open source: https://github.com/netless-io/flat-server

as long as you can deploy the server, you can basically distribute your application to the Internet.

of course you can also use our server, because we have already prepared the configuration file for you: https://github.com/netless-io/flat/tree/main/config

**Comment by meimosor** [comment]
Thank you, I have run the backend and electron client. But how does the web end run, and which branch is it?

**Comment by hyrious** [comment]
The web part is in the `web/flat-web` folder, to run it from the root folder:
```bash
yarn workspace flat-web start
```

**Comment by meimosor** [comment]
alright, thank you very much
